name: kickdown_app
description: Flutter implementation of Kickdown app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7
  flutter_inappwebview: ^4.0.0+4
  http: ^0.12.2
  intl: ^0.16.1
  provider: ^4.3.2+2
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ic_menu_more_normal.png
    - assets/2.0/ic_menu_more_normal.png
    - assets/3.0/ic_menu_more_normal.png
    - assets/ic_menu_more_selected.png
    - assets/2.0/ic_menu_more_selected.png
    - assets/3.0/ic_menu_more_selected.png
    - assets/ic_menu_overview_normal.png
    - assets/2.0/ic_menu_overview_normal.png
    - assets/3.0/ic_menu_overview_normal.png
    - assets/ic_menu_overview_selected.png
    - assets/2.0/ic_menu_overview_selected.png
    - assets/3.0/ic_menu_overview_selected.png
    - assets/ic_navbar_back.png
    - assets/2.0/ic_navbar_back.png
    - assets/3.0/ic_navbar_back.png
    - assets/ic_navbar_close.png
    - assets/2.0/ic_navbar_close.png
    - assets/3.0/ic_navbar_close.png
    - assets/ic_timer.png
    - assets/2.0/ic_timer.png
    - assets/3.0/ic_timer.png
    - assets/img_placeholder.png
    - assets/2.0/img_placeholder.png
    - assets/3.0/img_placeholder.png